--#################################################################################################
-- Snowflake-->  EDW_STG and EDW Pipelines --> Load Validations 
--#################################################################################################

--SRC to EDW_STG Data Load VALIDATIONS

SELECT 'REGIONS' AS Table_Name, COUNT(1) TABLE_COUNTS FROM EDW.EDW_STG.REGIONS
UNION ALL 
SELECT 'COUNTRIES' AS Table_Name, COUNT(1) TABLE_COUNTS FROM EDW.EDW_STG.COUNTRIES
UNION ALL 
SELECT 'LOCATIONS' AS Table_Name, COUNT(1) TABLE_COUNTS FROM EDW.EDW_STG.LOCATIONS 
UNION ALL 
SELECT 'DEPARTMENTS' AS Table_Name, COUNT(1) TABLE_COUNTS FROM EDW.EDW_STG.DEPARTMENTS
UNION ALL 
SELECT 'JOBS' AS Table_Name, COUNT(1) TABLE_COUNTS FROM EDW.EDW_STG.JOBS
UNION ALL
SELECT 'EMPLOYEES' AS Table_Name, COUNT(1) AS TABLE_COUNTS FROM EDW.EDW_STG.EMPLOYEES
UNION ALL 
SELECT 'JOB_HISTORY' AS Table_Name, COUNT(1) TABLE_COUNTS FROM EDW.EDW_STG.JOB_HISTORY ;

--EDW_STG to EDW Data Load VALIDATIONS

SELECT 'REGIONS' AS Table_Name, COUNT(1) TABLE_COUNTS FROM EDW.EDW.REGIONS
UNION ALL 
SELECT 'COUNTRIES' AS Table_Name, COUNT(1) TABLE_COUNTS FROM EDW.EDW.COUNTRIES
UNION ALL 
SELECT 'LOCATIONS' AS Table_Name, COUNT(1) TABLE_COUNTS FROM EDW.EDW.LOCATIONS 
UNION ALL 
SELECT 'DEPARTMENTS' AS Table_Name, COUNT(1) TABLE_COUNTS FROM EDW.EDW.DEPARTMENTS
UNION ALL 
SELECT 'JOBS' AS Table_Name, COUNT(1) TABLE_COUNTS FROM EDW.EDW.JOBS
UNION ALL
SELECT 'EMPLOYEES' AS Table_Name, COUNT(1) AS TABLE_COUNTS FROM EDW.EDW.EMPLOYEES
UNION ALL 
SELECT 'JOB_HISTORY' AS Table_Name, COUNT(1) TABLE_COUNTS FROM EDW.EDW.JOB_HISTORY
UNION ALL 
SELECT 'EMP_DETAILS_VIEW' AS Table_Name, COUNT(1) TABLE_COUNTS FROM EDW.EDW_EXTR.EMP_DETAILS_VIEW ;


-- TRUNCATE STG and EDW schemas tables, if required for debugging.

--STG Tables 

TRUNCATE TABLE EDW.EDW_STG.REGIONS;
TRUNCATE TABLE EDW.EDW_STG.COUNTRIES;
TRUNCATE TABLE EDW.EDW_STG.LOCATIONS;
TRUNCATE TABLE EDW.EDW_STG.DEPARTMENTS;
TRUNCATE TABLE EDW.EDW_STG.JOBS;
TRUNCATE TABLE EDW.EDW_STG.EMPLOYEES;
TRUNCATE TABLE EDW.EDW_STG.JOB_HISTORY;

--EDW Tables 

TRUNCATE TABLE EDW.EDW.REGIONS;
TRUNCATE TABLE EDW.EDW.COUNTRIES;
TRUNCATE TABLE EDW.EDW.LOCATIONS;
TRUNCATE TABLE EDW.EDW.DEPARTMENTS;
TRUNCATE TABLE EDW.EDW.JOBS;
TRUNCATE TABLE EDW.EDW.EMPLOYEES;
TRUNCATE TABLE EDW.EDW.JOB_HISTORY;